import { describe, it, expect } from "vitest";
import { generateDescriptionPrompt } from ".";

const sampleVtt = `WEBVTT - Auto-generated by https://github.com/dtinth/autosub

00:00:08.440 --> 00:00:11.040
Okay. Hi everyone.


00:00:12.840 --> 00:00:14.397
I'm super excited to be here.


00:00:14.480 --> 00:00:17.880
Thank you so much for joining my session.


00:00:18.320 --> 00:00:21.237
My name is Patt and I'm a content creator.


00:00:21.320 --> 00:00:23.919
I make creative coding content on YouTube


00:00:24.279 --> 00:00:31.276
and the mission of my channel is to inspire people


00:00:31.359 --> 00:00:34.879
to explore their creative potential through code.


00:00:35.559 --> 00:00:37.316
Today though, I'm going to be talking to you


00:00:37.399 --> 00:00:40.080
about the power of creative coding.


00:00:40.520 --> 00:00:41.397
But before we get there,


00:00:41.480 --> 00:00:44.719
I would like to ask you a quick question.


00:00:45.079 --> 00:00:48.599
What comes to mind when you think of the word coding?


00:00:48.920 --> 00:00:53.959
I'll give you a few seconds.


00:00:54.399 --> 00:00:56.440
Maybe it's writing a piece of code


00:00:56.760 --> 00:00:58.919
to tell the computer to do something.


00:01:00.600 --> 00:01:03.000
Maybe it's a person sitting at a desk


00:01:03.160 --> 00:01:05.517
trying to write this piece of instructions


00:01:05.600 --> 00:01:08.600
to create a functional software.


00:01:08.960 --> 00:01:12.197
Or maybe it is that very same person


00:01:12.280 --> 00:01:13.797
staring at a computer screen


00:01:13.880 --> 00:01:15.317
trying to figure out what is wrong


00:01:15.400 --> 00:01:17.676
with these piece of instructions.


00:01:17.759 --> 00:01:20.517
And these images don't really scream creativity


00:01:20.600 --> 00:01:23.639
or spark any joy, at least for me.`;

describe("generateDescriptionPrompt", () => {
  it("generates Thai language prompt with transcript", () => {
    const prompt = generateDescriptionPrompt(sampleVtt, "th");

    expect(prompt).toContain("Thai language");
    expect(prompt).toContain("<transcript>");
    expect(prompt).toContain("</transcript>");
    expect(prompt).toContain("<description>");
    expect(prompt).toContain('0:08,"Okay. Hi everyone."');
    expect(prompt).not.toContain("<chapters>");
  });

  it("generates English language prompt with transcript", () => {
    const prompt = generateDescriptionPrompt(sampleVtt, "en");

    expect(prompt).toContain("English language");
    expect(prompt).toContain("<transcript>");
    expect(prompt).toContain("</transcript>");
    expect(prompt).toContain("<description>");
    expect(prompt).toContain('0:08,"Okay. Hi everyone."');
  });

  it("handles empty VTT input without crashing", () => {
    const prompt = generateDescriptionPrompt("", "en");

    expect(prompt).toContain("<transcript>");
    expect(prompt).toContain("</transcript>");
    expect(prompt).toContain("<description>");
  });

  it("Thai prompt includes Thai-specific instructions and examples", () => {
    const prompt = generateDescriptionPrompt(sampleVtt, "th");

    expect(prompt).toContain("สุดล้ำ");
    expect(prompt).toContain("น่าทึ่ง");
    expect(prompt).toContain("ๆ");
    expect(prompt).toContain("getElementById");
    expect(prompt).toContain("โลกไร้งาน?");
    expect(prompt).toContain("JavaScript Mental Model");
    expect(prompt).toContain("Elysia");
    expect(prompt).toContain("Here are some examples of good description");
  });

  it("English prompt does not include Thai-specific instructions", () => {
    const prompt = generateDescriptionPrompt(sampleVtt, "en");

    expect(prompt).not.toContain("สุดล้ำ");
    expect(prompt).not.toContain("น่าทึ่ง");
    expect(prompt).not.toContain("ๆ");
  });
});
